services:
  _defaults:
    autowire: true

  TheIpster\IntegrationBranchBuilder\BitbucketCloud\FindPullRequestSourcesCommand:
    tags:
      - console.command
  TheIpster\IntegrationBranchBuilder\BitbucketCloud\FindPullRequestSourcesService: ~
