services:
  _defaults:
    autowire: true

  TheIpster\IntegrationBranchBuilder\BitbucketCloud\FindPullRequestSourcesService:
    arguments:
      $authHeaderValue: '%bitbucketCloud.authHeaderValue%'
      $organizationName: '%bitbucketCloud.organizationName%'
      $projectName: '%bitbucketCloud.projectName%'
  TheIpster\IntegrationBranchBuilder\BitbucketCloud\FindPullRequestSourcesCommand:
    tags:
      - console.command
