services:
  _defaults:
    autowire: true

  TheIpster\IntegrationBranchBuilder\BitbucketServer\FindPullRequestSourcesCommand:
    tags:
      - console.command
  TheIpster\IntegrationBranchBuilder\BitbucketServer\FindPullRequestSourcesService: ~
