services:
  _defaults:
    autowire: true

  TheIpster\IntegrationBranchBuilder\BitbucketServer\FindPullRequestSourcesService:
    arguments:
      $apiDomain: '%bitbucketServer.apiDomain%'
      $authHeaderValue: '%bitbucketServer.authHeaderValue%'
  TheIpster\IntegrationBranchBuilder\BitbucketServer\FindPullRequestSourcesCommand:
    tags:
      - console.command
